### ISSUE TITLE
Godot Plush mesh disappears when smashing.

### ISSUE THREAD

**Issue by antzGames** [cloudofoz/godot-smashthemesh#1]
* STM Add-on: Computing fractures for 'STMCachedInstance3D'
   . Tool initializing...
		# computing chunk 1/64
		# computing chunk 2/64
		# computing chunk 3/64
		# computing chunk 4/64
		# computing chunk 5/64
		# computing chunk 6/64
		# computing chunk 7/64
		# computing chunk 8/64
		# computing chunk 9/64
		# computing chunk 10/64
		# computing chunk 11/64
		# computing chunk 12/64
		# computing chunk 13/64
		# computing chunk 14/64
		# computing chunk 15/64
		# computing chunk 16/64
		# computing chunk 17/64
		# computing chunk 18/64
		# computing chunk 19/64
		# computing chunk 20/64
		# computing chunk 21/64
		# computing chunk 22/64
		# computing chunk 23/64
		# computing chunk 24/64
		# computing chunk 25/64
		# computing chunk 26/64
		# computing chunk 27/64
		# computing chunk 28/64
		# computing chunk 29/64
		# computing chunk 30/64
		# computing chunk 31/64
		# computing chunk 32/64
		# computing chunk 33/64
		# computing chunk 34/64
		# computing chunk 35/64
		# computing chunk 36/64
		# computing chunk 37/64
		# computing chunk 38/64
		# computing chunk 39/64
		# computing chunk 40/64
		# computing chunk 41/64
		# computing chunk 42/64
		# computing chunk 43/64
		# computing chunk 44/64
		# computing chunk 45/64
		# computing chunk 46/64
		# computing chunk 47/64
		# computing chunk 48/64
		# computing chunk 49/64
		# computing chunk 50/64
		# computing chunk 51/64
		# computing chunk 52/64
		# computing chunk 53/64
		# computing chunk 54/64
		# computing chunk 55/64
		# computing chunk 56/64
		# computing chunk 57/64
		# computing chunk 58/64
		# computing chunk 59/64
		# computing chunk 60/64
		# computing chunk 61/64
		# computing chunk 62/64
		# computing chunk 63/64
		# computing chunk 64/64
	. Adding physics to the chunks...
* Done.
	. Saving the cache to 'res://stm_cache/5118560892951.scn'
* Done.

But the Godot Plush mesh just disappears.

Before smash:
![image](https://github.com/user-attachments/assets/4b19e485-fc96-4658-84c1-6496f1ffc5b2)

After smash:
![image](https://github.com/user-attachments/assets/7a7b9c0c-4c7c-41df-84d1-1256db15370c)

**Comment by cloudofoz** [comment]
Hi @antzGames 

Thank you for your interest in my plugin! First, please try opening the cache scene located at "res://stm_cache/5118560892951.scn" to check if the mesh was fractured correctly.

If the cache scene appears to be fine, the issue may be related to a physics setting. Please let me know what you find!

**Comment by antzGames** [comment]
So nothing is shown when opening `res://stm_cache/5118560892951.scn` and its only 460 Bytes.  Just the STMChunks node with no children.

When I switch the mesh to a torus it works fine.  The error is in `stm_fracture_eat_a_chunk()` method.  

* STM Add-on: Computing fractures for 'STMCachedInstance3D'
   . Tool initializing...
		# computing chunk 1/8
Null
		# computing chunk 2/8
Null
		# computing chunk 3/8
Null
		# computing chunk 4/8
Null
		# computing chunk 5/8
Null
		# computing chunk 6/8
Null
		# computing chunk 7/8
Null
		# computing chunk 8/8
Null
	. Adding physics to the chunks...[]  count:(2, 2, 2)
* Done.
	. Saving the cache to 'res://stm_cache/5118560892951.scn'
* Done.

```python
func stm_fracture_eat_a_chunk(where: Vector3, chunk_data: Array) -> Mesh:
	
	# chunk_data := [0: chunk_mesh, 1: chunk_unique_vertices, 2: chunk_idx_map, 3: chunk_size, 4: chunk_noise, 5: optimize_flag, 6: chunk_vertices_threshold ]
	stm_fracture_gen_chunk(chunk_data)
	
	stm_csg_chunk_node.position = where

	stm_csg_chunk_node.operation = CSGShape3D.OPERATION_INTERSECTION
	var eaten_chunk: Mesh =  stm_grab_result_data()
	
	if eaten_chunk.get_surface_count() < 1 || eaten_chunk.surface_get_array_len(0) < chunk_data[6]:
		print("Null")
		return null
	
	if chunk_data[5]: # optimize
		eaten_chunk = stm_optimize_mesh(eaten_chunk)
	
	stm_csg_chunk_node.operation = CSGShape3D.OPERATION_SUBTRACTION
	stm_csg_source_node.mesh = stm_grab_result_data()
	
	return eaten_chunk

**Comment by cloudofoz** [comment]
Thank you for the update, @antzGames.

It seems that the issue is indeed related to the chunk generation of that mesh.

Could you please send me the mesh file or the scene file? You can either attach it here or email it to me. 
This could help me track down the problem.

I plan to run some initial tests on my system this evening, provided I can test with the scene or mesh that has the issue.

Thank you for your assistance!

**Comment by antzGames** [comment]
The mesh is taken from the middle sitting Godot Plush from this file:

[godot_plushV2.zip](https://github.com/user-attachments/files/17131481/godot_plushV2.zip)

**Comment by antzGames** [comment]
I will try it with other models.

**Comment by cloudofoz** [comment]
Good! I will try to test the mesh you provided later today.

**Comment by cloudofoz** [comment]
![godot_plush_sitted_rescaled](https://github.com/user-attachments/assets/c53cfb6f-004f-4540-bff5-c64c07f45266)

I've identified the issue, and it appears to be related to the **mesh scale**. The mesh you provided is too small, which causes the voxel grid used for computing fractures to malfunction.

I’ll need to rethink and rewrite the part of the code that handles scale normalization when I have more time to focus on it. In the meantime, I've attached a version of the mesh that has been upscaled in Blender, which should work better for now.

Thank you for bringing this problem to my attention!

[godot_plush_sitted_rescaled.zip](https://github.com/user-attachments/files/17133802/godot_plush_sitted_rescaled.zip)

**Comment by antzGames** [comment]
It works now.  So now that we know its a scaling/normalization problem, what sort of scale should a model target?  Its not hard to scale in Blender so if you just update the documentation, people can avoid this issue.

![image](https://github.com/user-attachments/assets/c5476cfe-976b-413d-9678-71f28fcbaa3d)

**Comment by cloudofoz** [comment]
I'm glad to hear it's working for you now as well.

Regarding the target scale, I'll need to investigate further to provide a more precise recommendation, but a good estimate would be that meshes should be at least 1 x 1 x 1 units, with at least one axis meeting or exceeding that threshold (preferably larger).

The mesh you provided was approximately 0.1 x 0.1 x 0.1 units, and after upscaling it by a factor of 50, it’s now around 5 x 5 x 5 units, which seems to perform much better.

I'll update the documentation to include a note on this issue until it's fully resolved, so others can avoid the same problem. Thanks again for bringing this to my attention.

**Comment by antzGames** [comment]
I created a video: https://youtu.be/qMXZnxzWs8s

Great work you are doing!

**Comment by cloudofoz** [comment]
Good job! Thank you for creating such a clear and helpful video. I appreciate how you explained the fundamentals in a direct, simple but complete way. I'll definitely add your video to the additional resources in the README.
