### ISSUE TITLE
No physics implementation possibility

### ISSUE THREAD

**Issue by antzGames** [cloudofoz/godot-smashthemesh#3]
Hello.

So I had a use case to not use physics at all.  I just need access to the mesh chunks, and will control them myself.

Secondly, I can setup physics to have no gravity, but the second reason I do not want physics is for performance.  I do not want to waste FPS on collision and physics, as I want the ability to only control the chunk meshes.

Anyhow, is there a way to build the STM cache with no rigid bodies and no collision shapes, and still define a custom callback?

I would not break the current implementation, but rather come up with a new node type **STMInstanced3DNoPhysics** or something like that, and will allow you to define a custom callback so you can control the chunks.

I may look into the plugin code and see if I can implement it myself, but I wanted you to know my idea.

**Comment by cloudofoz** [comment]
Hi @antzGames,

Currently STM doesn’t provide a straightforward way to build the cache without physics components. However, if you’re looking to bypass physics entirely, a good starting point is working with the `_stm_compute_fractures()` function.

In this function:

`var result = fracture.fracture(chunk_brush, chunk_count, opt)`

the `result `variable holds a list of the chunk meshes, allowing you to perform operations on them directly.

By stopping before the line that calls:

`rb_parent = PhysicsTool.gen_rigid_bodies(result, self)`

you can avoid generating rigid bodies.

In the future, I may explore adding an option to disable physics. This would involve a careful review and refactoring of the code, as there are various points that rely on rigid bodies and collision shapes.

Let me know how it goes if you decide to give this approach a try!

Best,
C.

**Comment by cloudofoz** [comment]
@antzGames : _"Secondly, I can setup physics to have no gravity,"_

In this case, the preferred way is to use:

- [`chunks_freeze(enable: bool)`](https://github.com/cloudofoz/godot-smashthemesh/#chunks_freezeenable-bool)
Description: Freezes or unfreezes the physics simulation of the chunks.

This allows you to easily operate on chunks without active physics, but it won’t remove the physics components themselves. You might want to try this approach to see if it’s feasible for your setup without affecting performance in a meaningful way.

**Comment by antzGames** [comment]
> a good starting point is working with the `_stm_compute_fractures()` function.

Yes, this is exactly what I did.   I got a solution working and but its too custom as a PR.

One suggestion is that you break **_stm_compute_fractures()** into 2 functions:

results = compute_fractures() -> array of Mesh`               # this is what I needed`
rb_parent = gen_rigid_bodies(results) -> Node3D

If you separate these then you can use your tool just a mesh smasher and allow the dev to use the fractured meshes how ever they choose.

Anyhow going to close this issue as I got what I need and you have some ideas to expand the use cases of this amazing addon.

Cheers!

**Comment by cloudofoz** [comment]
Physics and fracturing are already separated into two specific modules. You can use my `stm_fracture_tool.gd` as an independent module without the addon itself!

 `smash_the_mesh` is a convenience function to simplify the process.

Since you shouldn't operate transforms on the mesh node when you have physics, but only on rigid bodies, I developed the addon based on this concept.

Thank you for your suggestions, and good luck with your project!

**Comment by antzGames** [comment]
Make sure you turn up the volume.

Anyhow, great plugin.  So many ways to use it

https://github.com/user-attachments/assets/9179f9de-f0a3-4fa6-a3e0-8aa7907c70e8

**Comment by cloudofoz** [comment]
Nice work using STM to make those enemies explode!
There's definitely something oddly satisfying about your playtest 😄
Looking forward to seeing your progress! I'm glad the plugin’s been useful, keep up the cool work!
