### ISSUE TITLE
Q: Easy way to clean up all chunks?

### ISSUE THREAD

**Issue by zaknafean** [cloudofoz/godot-smashthemesh#4]
In my game I keep hitting some edge cases where a level will end and I won't have had at time for the generated to chunks to clear themselves. Is there any easy built in way to get a list of all generated chunks in the tree and act on them?

**Comment by cloudofoz** [comment]
Hi @zaknafean,

If you're looking to simply remove the chunks after a level ends, you might find these methods helpful:

- [`chunks_kill()`](https://github.com/cloudofoz/godot-smashthemesh?tab=readme-ov-file#chunks_kill)
Description: Removes all the chunks of this mesh instance.

- [`chunks_reset()`](https://github.com/cloudofoz/godot-smashthemesh?tab=readme-ov-file#chunks_reset)
Description: Resets this instance to its state before `smash_the_mesh()` was called.

Alternatively, if you need to perform a custom action on each chunk (like an animation or state update), you can use:

- [`chunks_iterate(callback: Callable)`](https://github.com/cloudofoz/godot-smashthemesh?tab=readme-ov-file#chunks_iteratecallback-callable)
Description: Iterates over all the chunks' `RigidBody3D` instances, allowing you to perform operations on the chunks of this instance.

Let me know if this helps resolve your issue!

C.

**Comment by zaknafean** [comment]
But there isn't a centralized way to remove all of them correct? Guess I can run these in an exit hook. I'll try it out tonight.

**Comment by cloudofoz** [comment]
You may want to try this code snippet from the scene root node to remove all the chunks:

```gdscript
var smashables = find_children("", "STMCachedInstance3D", true, false)
for s in smashables:
    s.chunks_kill()
```

Let me know if this addresses your problem!

**Comment by cloudofoz** [comment]
Hi @zaknafean,

since there hasn’t been an update in a few days, I’ll go ahead and close this issue for now. If the code snippet didn’t fully address your problem or if you have any other questions, please feel free to reopen it or start a new issue.
